# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedflatpage',
            name='flatpage_ptr',
        ),
        migrations.DeleteModel(
            name='ExtendedFlatPage',
        ),
    ]
