# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='7b547c7b1b', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modify datetime')),
                ('slug', models.SlugField(help_text='slug for URLs')),
                ('description', models.TextField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('website', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, default='images/avatars/avatar.png', upload_to='images/avatars/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
