# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='slug for URLs'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default='7c484125ff', max_length=10),
        ),
    ]
